import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log(session, "session");
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center gap-7 mb-[10px] bg-white p-6">
          <div className="font-bold text-[20px]">
            <Link href="/">LearningNEXTJS</Link>
          </div>
          <Link href="/list">List</Link>
          <form action="/api/time" method="get" className="flex justify-center">
            <Link href="/api/time">Now</Link>
          </form>
          <div className="ml-auto">
            {session ? (
              <>
                <span className="mr-4">안녕하세요, {session.user.name} 님</span>
                <LogoutBtn />
              </>
            ) : (
              <LoginBtn />
            )}
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
