import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center gap-7 bg-white p-6 dark:bg-slate-800 dark:text-white">
          <div className="font-bold text-[20px]">
            <Link href="/">LearningNEXTJS</Link>
          </div>
          <Link href="/list">List</Link>
          <form action="/api/time" method="get" className="flex justify-center">
            <Link href="/api/time">Now</Link>
          </form>
          <div className="ml-auto">
            {session ? (
              <>
                <span className="mr-4">안녕하세요, {session.user.name} 님</span>
                <LogoutBtn />
              </>
            ) : (
              <>
                <span className="mr-2">
                  <Link href="/signup">sign up</Link>
                </span>
                <LoginBtn />
              </>
            )}
          </div>
          <DarkMode />
        </div>
        <div className="p-10 w-full h-real-screen bg-white dark:bg-slate-800">
          {children}
        </div>
      </body>
    </html>
  );
}
